# Generated by Django 4.1.1 on 2022-11-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildings",
            name="building_price",
            field=models.PositiveSmallIntegerField(
                default=3000, verbose_name="Цена здания"
            ),
        ),
        migrations.AddField(
            model_name="militarybuildings",
            name="building_price",
            field=models.PositiveSmallIntegerField(
                default=3000, verbose_name="Цена здания"
            ),
        ),
        migrations.AddField(
            model_name="resourcebuildings",
            name="building_price",
            field=models.PositiveSmallIntegerField(
                default=3000, verbose_name="Цена здания"
            ),
        ),
    ]
