# Generated by Django 4.1.1 on 2022-11-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Орки_1", "Орки"),
                            ("Эльфы_2", "Эльфы"),
                            ("Гномы_3", "Гномы"),
                            ("Люди_4", "Люди"),
                        ],
                        max_length=25,
                        verbose_name="Раса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раса",
                "verbose_name_plural": "Расы",
                "db_table": "race",
                "ordering": ["name"],
            },
        ),
    ]
