# Generated by Django 4.1.1 on 2022-11-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_registered",
            field=models.BooleanField(default=False, verbose_name="Статус регистрации"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность"),
        ),
    ]
